services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - redis-network
    restart: unless-stopped

networks:
  redis-network:
    external: true
